version: "3.7"
services:
  traefik:
    image: traefik:${PROXY_VERSION?latest}
    container_name: traefik
    command:
      - "--api.insecure=true"
      - "--providers.docker.exposedbydefault=false"
      - "--providers.docker.watch=true"
      - "--providers.docker.network=traefik-public"
      - "--entrypoints.web.address=:80"
      - "--entrypoints.websecure.address=:443"
      - "--certificatesresolvers.letsencrypt.acme.email=${PROXY_EMAIL}"
      - "--certificatesresolvers.letsencrypt.acme.caServer=https://acme-v02.api.letsencrypt.org/directory"
      - "--certificatesresolvers.letsencrypt.acme.storage=acme.json"
      - "--certificatesresolvers.letsencrypt.acme.httpChallenge.entryPoint=web"
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./conf/acme.json:/acme.json
    restart: always
    labels:
      - 'traefik.enable=true'
      - 'traefik.http.routers.api.rule=Host(`${PROXY_DOMAIN}`) && (PathPrefix(`/api`) || PathPrefix(`/dashboard`))'
      - 'traefik.http.routers.api.service=api@internal'
      - 'traefik.http.routers.api.entrypoints=websecure'
      - 'traefik.http.routers.api.middlewares=auth'
      - "traefik.http.routers.api.tls=true"
      - 'traefik.http.middlewares.auth.basicauth.users=${PROXY_BASIC_AUTH}'
      - "traefik.http.routers.api.tls.certresolver=letsencrypt"
      - "traefik.http.middlewares.api-https.redirectscheme.scheme=https"
    networks:
      - traefik-public

  portainer:
    image: portainer/portainer-ce:${PORTAINER_VERSION?latest}
    container_name: portainer
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    networks:
      - traefik-public
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./portainer-data:/data
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.portainer.tls=true"
      - "traefik.http.routers.portainer.entrypoints=websecure"
      - "traefik.http.routers.portainer.rule=Host(`${PORTAINER_DOMAIN}`)"
      - "traefik.http.routers.portainer.service=portainer"
      - "traefik.http.services.portainer.loadbalancer.server.port=${PORTAINER_PORT?9000}"
      - "traefik.http.routers.portainer.tls.certresolver=letsencrypt"
      - "traefik.http.middlewares.portainer-https.redirectscheme.scheme=https"

networks:
  traefik-public:
    external: true